nome = str(input('Digite o seu nome completo: '))
print(f'Muito prazer em te conhecer {nome}!')
nome = nome.split()
print(f'O seu primeiro nome é {nome[0]}')
print(f'O seu último nome é {nome[-1]}')
